dist: trusty
sudo: required
cache:
  apt: true
  pip: false
language: python
python:
  - "2.7"
  - "3.5"

before_install:
  # Add apt sources
  - sudo -E apt-add-repository -y ppa:george-edison55/cmake-3.x
  - echo deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse | sudo tee /etc/apt/sources.list.d/trusty-backports.list
  - sudo apt-get update -qq

  # Install CMake >= 3 for pachi-py
  - sudo apt-get -y install cmake cmake-data python-dev libav-tools

  # Install SWIG >= 3 for box2d-py (See #83).
  - sudo apt-get -y install -t trusty-backports swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig

  # Fetch Mujoco. When testing a pull request, we don't have the Travis
  # secrets, and hence no Mujoco.
  - mkdir -p ~/.mujoco
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ( curl https://openai-public.s3-us-west-2.amazonaws.com/mujoco/$MUJOCO_KEY_BUNDLE.tar.gz | tar xz -C ~/.mujoco )'

  # Start a framebuffer for our windows to render to
  - Xvfb :12 -screen 0 800x600x24 +extension RANDR &

env:
  - DISPLAY=:12
install: pip install tox-travis
script: tox

notifications:
  slack:
    secure: h/Mxm8K+avH/2W0818zCHmLloRPMFN4NJL01+VShvAkH80/acfjeq/+mMdWXXPL/oOB6kSHDk+GDhwR6+s03ZcPMn5INTFvFYqUc6UWmT+NXtOPxGTN0xda6MdYUkWQUKaMyjFrweZQOMOASFBIzPOq4XeVbM5aB8s4EJhnfAcYZhp/idwKbToVihN4KZgxlvZIFc8iEp1o9uSl5qrsaeYYYXRkb6mauacAwOo4/Chu+cOnoLUOnvhBFE3rV3doDNrbnoalO8XiExtgx5CIAYWrlMni7r2Q+LlzgwdyTH19ZtybPxJTZIIWSBQ2UtcoYdIEDcc36GcUwz1VUGg32mLJJnY2xw80CWR4ixFPpLwwP5Y99WTn8v094B4nmFTWOwNWXp3EkqtTN9XcJoRBqXB5ArucIPqrx57dOCljSKx22gL6WaF2p3stSAxIGFektGyGnisaELrFZG1C63aHoUPicj3gUlijmAoUmYaDRf6P1wnpXqBpKDAWWhAMSatvx1ekmEJgR7OQklQnnfjx9kENDUygNUWS4IQwN2qYieuzHFL3of7/30mTM43+Vt/vWN8GI7j01BXu6FNGGloHxjH1pt3bLP/+uj5BJsT2HWF+Z8XR4VE6cyVuKsQAFgCXwOkoDHALbcwsspONDIt/9ixkesgh1oFt4CzU3UuU5wYs=
    on_success: change
