dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
env:
  # - UBUNTU_VER=14.04 - problems with atari-py
  - PY_VER=2.7
  - PY_VER=3.5.6
  - PY_VER=3.6.8
  - PY_VER=3.7.3

install: "" # so travis doesn't do pip install requirements.txt
script:
  - docker build -f py.Dockerfile --build-arg MUJOCO_KEY=$MUJOCO_KEY --build-arg PYTHON_VER=$PY_VER -t gym-test .
  - docker run gym-test 

deploy:
    provider: pypi
    username: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
        tags: true
        condition: $PY_VER = 3.5.6
