dist: trusty
sudo: required
cache:
  apt: true
  pip: true
language: python
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
      - deadsnakes
    packages:
      - cmake
      - cmake-data
      - python-dev
      - python3.4-dev
      - swig
      - libav-tools
      - python-numpy
      - libboost-all-dev
      - libsdl2-dev
      - libjpeg-dev
      - zlib1g-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
python:
  - "2.7"
  - "3.4"
before_install:
  - Xvfb :12 -screen 0 800x600x24 +extension RANDR &
    # In a pull request, there are no secrets, and hence no MuJoCo:
    # https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests.
  - '[ -z ${MUJOCO_KEY_BUNDLE+x} ] || ( mkdir -p ~/.mujoco && curl https://openai-public.s3-us-west-2.amazonaws.com/mujoco/$MUJOCO_KEY_BUNDLE.tar.gz | tar xz -C ~/.mujoco )'
  # Without this line, Travis has fork()s fail with an out of memory
  # error. (These fork()s are for spawning the subprocess for video
  # recording.) We should debug the memory usage at some stage, but
  # simply setting overcommit is a good starting point.
  - sudo sysctl -w vm.overcommit_memory=1
  # Installs Miniconda to avoid having to compile NumPy, SciPy, etc.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh && chmod +x miniconda.sh && ./miniconda.sh -b && export PATH=$HOME/miniconda2/bin:$PATH && conda update --yes conda
env:
  - DISPLAY=:12
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - nose2

notifications:
  slack:
    secure: h/Mxm8K+avH/2W0818zCHmLloRPMFN4NJL01+VShvAkH80/acfjeq/+mMdWXXPL/oOB6kSHDk+GDhwR6+s03ZcPMn5INTFvFYqUc6UWmT+NXtOPxGTN0xda6MdYUkWQUKaMyjFrweZQOMOASFBIzPOq4XeVbM5aB8s4EJhnfAcYZhp/idwKbToVihN4KZgxlvZIFc8iEp1o9uSl5qrsaeYYYXRkb6mauacAwOo4/Chu+cOnoLUOnvhBFE3rV3doDNrbnoalO8XiExtgx5CIAYWrlMni7r2Q+LlzgwdyTH19ZtybPxJTZIIWSBQ2UtcoYdIEDcc36GcUwz1VUGg32mLJJnY2xw80CWR4ixFPpLwwP5Y99WTn8v094B4nmFTWOwNWXp3EkqtTN9XcJoRBqXB5ArucIPqrx57dOCljSKx22gL6WaF2p3stSAxIGFektGyGnisaELrFZG1C63aHoUPicj3gUlijmAoUmYaDRf6P1wnpXqBpKDAWWhAMSatvx1ekmEJgR7OQklQnnfjx9kENDUygNUWS4IQwN2qYieuzHFL3of7/30mTM43+Vt/vWN8GI7j01BXu6FNGGloHxjH1pt3bLP/+uj5BJsT2HWF+Z8XR4VE6cyVuKsQAFgCXwOkoDHALbcwsspONDIt/9ixkesgh1oFt4CzU3UuU5wYs=
    on_success: change
