[tool.pyright]

include = [
    "gym/**",
    "tests/**"
]

exclude = [
    "**/node_modules",
    "**/__pycache__",

    "gym/envs/box2d/bipedal_walker.py",
#    "gym/envs/box2d/lunar_lander.py",
    "gym/envs/box2d/car_racing.py",

    "gym/spaces/graph.py",

    "gym/envs/mujoco/**",
    "gym/utils/play.py",

    "gym/vector/async_vector_env.py",
    "gym/vector/utils/__init__.py",

    "gym/wrappers/atari_preprocessing.py",
    "gym/wrappers/gray_scale_observation.py",
    "gym/wrappers/human_rendering.py",
    "gym/wrappers/normalize.py",
    "gym/wrappers/pixel_observation.py",
    "gym/wrappers/record_video.py",
    "gym/wrappers/monitoring/video_recorder.py",
    "gym/wrappers/resize_observation.py",

    "tests/envs/test_env_implementation.py",
    "tests/utils/test_play.py",
    "tests/vector/test_async_vector_env.py",
    "tests/vector/test_shared_memory.py",
    "tests/vector/test_spaces.py",
    "tests/vector/test_sync_vector_env.py",
    "tests/vector/test_vector_env.py",
    "tests/wrappers/test_gray_scale_observation.py",
    "tests/wrappers/test_order_enforcing.py",
    "tests/wrappers/test_record_episode_statistics.py",
    "tests/wrappers/test_resize_observation.py",
    "tests/wrappers/test_time_aware_observation.py",
    "tests/wrappers/test_video_recorder.py",

]

strict = [

]

typeCheckingMode = "basic"
pythonVersion = "3.6"
typeshedPath = "typeshed"
enableTypeIgnoreComments = true

# This is required as the CI pre-commit does not download the module (i.e. numpy, pygame, box2d)
#   Therefore, we have to ignore missing imports
reportMissingImports = "none"

reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportPrivateUsage = "warning"
reportUntypedFunctionDecorator = "none"
reportMissingTypeStubs = false
reportUnboundVariable = "warning"
reportGeneralTypeIssues = "none"
reportInvalidTypeVarUse = "none"